server:
  port: 8762

spring:
  application:
    name: cache-services
  devtools:
    restart:
      enabled: true
      additional-paths: src/main
  redis:
      #host: 'my_redis'
      host: 'localhost'
      port: 6379
#      lettuce:
#        pool:
#          max-wait: 100000
#          max-idle: 10
#          max-active: 100
      timeout: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


