server:
  port: 8762

spring:
  application:
    name: redis-services
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/views/
    suffix: .html
    encoding: UTF-8
#    content-type: text/html
  mvc:
    static-path-pattern: /**
  devtools:
    restart:
      enabled: true
      additional-paths: src/main



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

redis:
    host: localhost
    port: 6379
