server:
  port: 8762

spring:
  application:
    name: cache-services
 # thymeleaf:
 #   cache: false
 #   mode: LEGACYHTML5
 #   prefix: classpath:/views/
 #   suffix: .html
 #   encoding: UTF-8
 #   content-type: text/html
  mvc:
 #   static-path-pattern: /**
  devtools:
    restart:
      enabled: true
      additional-paths: src/main
  redis:
      #host: 'my_redis'
      host: 'localhost'
      port: 6379


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


